### PR TITLE
Remove unused paper-ripple

### PR DESCRIPTION
**Pull request by abdonrd**
Also, change `polymerelements` to `PolymerElements`

### CODE REVIEW

**Comment by keanulee** [comment]
`paper-ripple` is used and is dynamically created by `PaperRippleBehavior`

**Comment by abdonrd** [comment]
@keanulee Yes, but the `paper-button-behavior.html` imports the `paper-ripple-behavior.html` that imports the `paper-ripple.html`. :)

**Comment by keanulee** [comment]
Yes, but paper-behavior's `bower.json` lists paper-ripple as a dev dependency. I guess the HTML import isn't _technically_ needed in paper-button.html though.

**Comment by abdonrd** [comment]
@keanulee I understand!

Now I've done the following:
- Checkout to this PR branch.
- Remove the `bower_components`.
- Run `bower i`

And the demo works fine with the `paper-ripple`.

**Comment by keanulee** [comment]
@abdonrd If you `bower install --production` though, you'll see the paper-ripple is not included. The reason why `paper-ripple` was included is because (at least) one of the dev dependency is included the latest released version of `paper-button`, which includes `paper-ripple`

**Comment by abdonrd** [comment]
@keanulee oh! Now I understand much better. Thanks!

Then... The right thing would be that `paper-behaviors` include `paper-ripple` as `dependencies` instead of `devDependencies`. Right?

**Comment by keanulee** [comment]
@abdonrd Yes, `paper-ripple` should be a dependency of `paper-behaviors` - it has an HTML import for it too (https://github.com/PolymerElements/paper-behaviors/blob/master/paper-ripple-behavior.html#L12). Mind sending a PR for that, and we'll revisit this once that's been done and released?

**Comment by abdonrd** [comment]
@keanulee sure! We can fix it! :smiley:

**Comment by abdonrd** [comment]
@keanulee now we can open and merge this? :smiley:

**Comment by keanulee** [comment]
I can't reopen this PR because GitHub won't let me ("The remove_unused_import branch was force-pushed or recreated"). Feel free to submit a new PR.

**Pull request closed without merging**
