### PR TITLE
Add 'is' to paper-button

### PR DESCRIPTION
**Pull request by jklein24**

### CODE REVIEW

**Comment by cdata** [comment]
@garlicnation @jklein24 with complete respect and acknowledgement towards how frustrating it would be from a tooling perspective if elements didn't have `is` on them, @sjmiles would like us to debate the various merits before removing this.

**Comment by cdata** [comment]
Also, there was a typo that raises a syntax error: missing closing quotation mark on the string :(

**Comment by cdata** [comment]
(the irony here is that if we were running the compiler pass as part of our tests, we wouldn't have caught that).

**Comment by jklein24** [comment]
Sorry about the syntax error!! I'm happy to talk this through with Scott because it breaks the compiled use case in a couple different ways. The good news is that the compiler pass did catch this error:

 ERROR - Parse error. Unterminated string literal
    is: 'paper-button,

**Comment by jklein24** [comment]
@sjmiles, can we hash this out? It's currently breaking use of paper-button inside Google and Chrome.

**Pull request merged**
