### PR TITLE
Fix for document.createElement('paper-button') DOMException

### LINKED ISSUE #144: document.createElement('paper-button') DOMException
### Description

With the latest 2.0-preview branch, if I do `document.createElement('paper-button');`, I am getting a DOMException.

This seems to be caused by the below code in `paper-button`.
```
created: function() {
        this.classList.add('paper-material');
      },
```

Changing that to use `connectedCallback` seems to fix the issue.

### Expected outcome

No Error

### Actual outcome

DOMException:
```
Uncaught DOMException: Failed to construct 'CustomElement': The result must not have attributes
    at <anonymous>:1:10
```

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari 9
- [x] Safari 8
- [x] Safari 7
- [x] Edge
- [x] IE 11
- [x] IE 10

### PR DESCRIPTION
**Pull request by jaichandra**

### CODE REVIEW

**Comment by jaichandra** [comment]
I signed the CLA.

**Comment by jaichandra** [comment]
@lychyi My code is now broken due to the changes in 2.0 branch. Will refactor and check. but yeah.. as per docs, for legacy elements it should be `attached`. Demo works with `attached`.

**Comment by jaichandra** [comment]
`attached` works.

**Comment by lychyi** [comment]
Fantastic @jaichandra nice work! Everything looks good on my end. Hopefully the team can get this merged soon. I ran into this when extending paper-button with the new 2.0 class syntax and it caused quite a headache.

**Comment by notwaldorf** [comment]
This is no longer needed, since we're not putting the `paper-material` class on the host anymore

**Pull request closed without merging**
